# Generated by Django 2.2.1 on 2020-05-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200504_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Book'),
        ),
    ]
